-- Group name: group3
-- Authors: Tan Pei Sheng (32185235), 
--          Hou Ruiqian (31921183), 
--          Rebecca Nga (30720591)

-- capture run of script in file called wc_schema_output.txt
set echo on
SPOOL wc_schema_output.txt
-- Generated by Oracle SQL Developer Data Modeler 21.4.1.349.1605
--   at:        2022-04-27 21:38:42 MYT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

DROP TABLE cabin CASCADE CONSTRAINTS;

DROP TABLE country CASCADE CONSTRAINTS;

DROP TABLE cruise CASCADE CONSTRAINTS;

DROP TABLE cruise_port CASCADE CONSTRAINTS;

DROP TABLE language CASCADE CONSTRAINTS;

DROP TABLE manifest CASCADE CONSTRAINTS;

DROP TABLE operator CASCADE CONSTRAINTS;

DROP TABLE passenger CASCADE CONSTRAINTS;

DROP TABLE passenger_addr CASCADE CONSTRAINTS;

DROP TABLE port CASCADE CONSTRAINTS;

DROP TABLE port_temp CASCADE CONSTRAINTS;

DROP TABLE ship CASCADE CONSTRAINTS;

DROP TABLE tour CASCADE CONSTRAINTS;

DROP TABLE tour_availability CASCADE CONSTRAINTS;

DROP TABLE tour_comm_language CASCADE CONSTRAINTS;

DROP TABLE tour_passenger CASCADE CONSTRAINTS;

DROP TABLE tour_report CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE cabin (
    cabin_no       CHAR(3) NOT NULL,
    ship_code      CHAR(6) NOT NULL,
    cabin_capacity NUMBER(2) NOT NULL,
    cabin_class    CHAR(1) NOT NULL
);

ALTER TABLE cabin
    ADD CONSTRAINT chk_cabin_class CHECK ( cabin_class IN ( 'B', 'I', 'O', 'S' ) );

COMMENT ON COLUMN cabin.cabin_no IS
    'Cabin Number';

COMMENT ON COLUMN cabin.ship_code IS
    'Ship code';

COMMENT ON COLUMN cabin.cabin_capacity IS
    'Cabin''s max guest capacity';

COMMENT ON COLUMN cabin.cabin_class IS
    'Cabin''s class- I(nterior), O(cean view), B(alcony), S(uite)';

ALTER TABLE cabin ADD CONSTRAINT cabin_pk PRIMARY KEY ( cabin_no,
                                                        ship_code );

CREATE TABLE country (
    country_code CHAR(2) NOT NULL,
    country_name VARCHAR2(60) NOT NULL
);

COMMENT ON COLUMN country.country_code IS
    'Country code in ISO 3166-1 Alpha-2 format';

COMMENT ON COLUMN country.country_name IS
    'Country full name';

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( country_code );

CREATE TABLE cruise (
    cruise_id   CHAR(4) NOT NULL,
    cruise_name VARCHAR2(50) NOT NULL,
    cruise_desc VARCHAR2(200),
    ship_code   CHAR(6) NOT NULL
);

COMMENT ON COLUMN cruise.cruise_id IS
    'Cruise ID';

COMMENT ON COLUMN cruise.cruise_name IS
    'Cruise''s name';

COMMENT ON COLUMN cruise.cruise_desc IS
    'Description/additional info about cruise';

COMMENT ON COLUMN cruise.ship_code IS
    'Ship code';

ALTER TABLE cruise ADD CONSTRAINT cruise_pk PRIMARY KEY ( cruise_id );

CREATE TABLE cruise_port (
    cruise_id   CHAR(4) NOT NULL,
    port_code   CHAR(5) NOT NULL,
    cp_datetime DATE NOT NULL
);

COMMENT ON COLUMN cruise_port.cruise_id IS
    'Cruise ID';

COMMENT ON COLUMN cruise_port.port_code IS
    'Port code';

COMMENT ON COLUMN cruise_port.cp_datetime IS
    'Cruise port depature/arrival datetime';

ALTER TABLE cruise_port ADD CONSTRAINT cruise_port_pk PRIMARY KEY ( cruise_id,
                                                                    port_code );

CREATE TABLE language (
    language_code CHAR(2) NOT NULL,
    language_name VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN language.language_code IS
    'The code for language  stored as ISO 639-1 Alpha-2 codes';

COMMENT ON COLUMN language.language_name IS
    'The language name';

ALTER TABLE language ADD CONSTRAINT language_pk PRIMARY KEY ( language_code );

CREATE TABLE manifest (
    passenger_id      CHAR(5) NOT NULL,
    cruise_id         CHAR(4) NOT NULL,
    boarding_datetime DATE NOT NULL,
    cabin_no          CHAR(3) NOT NULL,
    ship_code         CHAR(6) NOT NULL
);

COMMENT ON COLUMN manifest.passenger_id IS
    'Passenger ID';

COMMENT ON COLUMN manifest.cruise_id IS
    'Cruise ID';

COMMENT ON COLUMN manifest.boarding_datetime IS
    'Passenger cruise boarding date and time';

COMMENT ON COLUMN manifest.cabin_no IS
    'Cabin Number';

COMMENT ON COLUMN manifest.ship_code IS
    'Ship code';

ALTER TABLE manifest ADD CONSTRAINT manifest_pk PRIMARY KEY ( passenger_id,
                                                              cruise_id );

CREATE TABLE operator (
    operator_id       CHAR(8) NOT NULL,
    operator_company  VARCHAR2(50) NOT NULL,
    operator_ceo_name VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN operator.operator_id IS
    'Operator ID';

COMMENT ON COLUMN operator.operator_company IS
    'Operator''s registered company name';

COMMENT ON COLUMN operator.operator_ceo_name IS
    'Operator CEO Name';

ALTER TABLE operator ADD CONSTRAINT operator_pk PRIMARY KEY ( operator_id );

CREATE TABLE passenger (
    passenger_id        CHAR(5) NOT NULL,
    passenger_fname     VARCHAR2(50) NOT NULL,
    passenger_lname     VARCHAR2(50) NOT NULL,
    passenger_gender    CHAR(1) NOT NULL,
    passenger_dob       DATE NOT NULL,
    passenger_lang      CHAR(2) NOT NULL,
    passenger_phone     VARCHAR2(15) NOT NULL,
    passenger_addr_code CHAR(8) NOT NULL,
    language_code       CHAR(2) NOT NULL,
    guardian_id         CHAR(5)
);

ALTER TABLE passenger
    ADD CONSTRAINT check_gender CHECK ( passenger_gender IN ( 'F', 'M', 'O' ) );

COMMENT ON COLUMN passenger.passenger_id IS
    'Passenger ID';

COMMENT ON COLUMN passenger.passenger_fname IS
    'Passenger''s first name';

COMMENT ON COLUMN passenger.passenger_lname IS
    'Passenger''s last name';

COMMENT ON COLUMN passenger.passenger_gender IS
    'Passenger''s gender - F(emale)/M(ale)/O(ther)';

COMMENT ON COLUMN passenger.passenger_dob IS
    'Passenger''s date of birth';

COMMENT ON COLUMN passenger.passenger_lang IS
    'Passenger Primary Language';

COMMENT ON COLUMN passenger.passenger_phone IS
    'Passenger phone number including country code prefix - 15 digits max';

COMMENT ON COLUMN passenger.passenger_addr_code IS
    'surrogate key for passenger''s address';

COMMENT ON COLUMN passenger.language_code IS
    'The code for language  stored as ISO 639-1 Alpha-2 codes';

COMMENT ON COLUMN passenger.guardian_id IS
    'Passenger ID';

ALTER TABLE passenger ADD CONSTRAINT passenger_pk PRIMARY KEY ( passenger_id );

CREATE TABLE passenger_addr (
    passenger_addr_code     CHAR(8) NOT NULL,
    passenger_addr_street   VARCHAR2(100) NOT NULL,
    passenger_addr_town     VARCHAR2(50) NOT NULL,
    passenger_addr_postcode VARCHAR2(10) NOT NULL,
    country_code            CHAR(2) NOT NULL
);

COMMENT ON COLUMN passenger_addr.passenger_addr_code IS
    'surrogate key for passenger''s address';

COMMENT ON COLUMN passenger_addr.passenger_addr_street IS
    'Passenger''s address street';

COMMENT ON COLUMN passenger_addr.passenger_addr_town IS
    'Passenger''s address town';

COMMENT ON COLUMN passenger_addr.passenger_addr_postcode IS
    'Passenger''s address postcode';

COMMENT ON COLUMN passenger_addr.country_code IS
    'Country code in ISO 3166-1 Alpha-2 format';

ALTER TABLE passenger_addr ADD CONSTRAINT passenger_addr_pk PRIMARY KEY ( passenger_addr_code );

ALTER TABLE passenger_addr
    ADD CONSTRAINT passenger_addr_nk UNIQUE ( passenger_addr_street,
                                              passenger_addr_town,
                                              passenger_addr_postcode,
                                              country_code );

CREATE TABLE port (
    port_code       CHAR(5) NOT NULL,
    port_name       VARCHAR2(50) NOT NULL,
    port_population NUMBER(10) NOT NULL,
    port_longitude  NUMBER(10, 7) NOT NULL,
    port_latitude   NUMBER(10, 7) NOT NULL,
    country_code    CHAR(2) NOT NULL
);

COMMENT ON COLUMN port.port_code IS
    'Port code';

COMMENT ON COLUMN port.port_name IS
    'Port''s name';

COMMENT ON COLUMN port.port_population IS
    'Port population';

COMMENT ON COLUMN port.port_longitude IS
    'Port longitude';

COMMENT ON COLUMN port.port_latitude IS
    'Port latitude';

COMMENT ON COLUMN port.country_code IS
    'Country code in ISO 3166-1 Alpha-2 format';

ALTER TABLE port ADD CONSTRAINT port_pk PRIMARY KEY ( port_code );

CREATE TABLE port_temp (
    port_code     CHAR(5) NOT NULL,
    temp_month    CHAR(3) NOT NULL,
    temp_avg_high NUMBER(2),
    temp_avg_low  NUMBER(2)
);

ALTER TABLE port_temp
    ADD CONSTRAINT chk_month CHECK ( temp_month IN ( 'APR', 'AUG', 'DEC', 'FEB', 'JAN',
                                                     'JUL', 'JUN', 'MAR', 'MAY', 'NOV',
                                                     'OCT', 'SEP' ) );

COMMENT ON COLUMN port_temp.port_code IS
    'Port code';

COMMENT ON COLUMN port_temp.temp_month IS
    'The time month for temperature at port';

COMMENT ON COLUMN port_temp.temp_avg_high IS
    'average high temperature of a month';

COMMENT ON COLUMN port_temp.temp_avg_low IS
    'average low temperature for a month';

ALTER TABLE port_temp ADD CONSTRAINT port_temp_pk PRIMARY KEY ( temp_month,
                                                                port_code );

CREATE TABLE ship (
    ship_code     CHAR(6) NOT NULL,
    ship_name     VARCHAR2(50) NOT NULL,
    ship_date     DATE NOT NULL,
    ship_tonnage  NUMBER(6) NOT NULL,
    ship_capacity NUMBER(5) NOT NULL,
    country_code  CHAR(2) NOT NULL,
    operator_id   CHAR(8) NOT NULL
);

COMMENT ON COLUMN ship.ship_code IS
    'Ship code';

COMMENT ON COLUMN ship.ship_name IS
    'Ship''s name';

COMMENT ON COLUMN ship.ship_date IS
    'Date when ship was commissioned';

COMMENT ON COLUMN ship.ship_tonnage IS
    'Ship''s tonnage';

COMMENT ON COLUMN ship.ship_capacity IS
    'Ship''s maximum guest capacity';

COMMENT ON COLUMN ship.country_code IS
    'Country code in ISO 3166-1 Alpha-2 format';

COMMENT ON COLUMN ship.operator_id IS
    'Operator ID';

ALTER TABLE ship ADD CONSTRAINT ship_pk PRIMARY KEY ( ship_code );

CREATE TABLE tour (
    port_code          CHAR(5) NOT NULL,
    tour_no            CHAR(2) NOT NULL,
    tour_name          VARCHAR2(100) NOT NULL,
    tour_desc          VARCHAR2(200) NOT NULL,
    tour_hours         NUMBER(3, 1) NOT NULL,
    tour_cost          NUMBER(4) NOT NULL,
    tour_wheel_chair   CHAR(1) NOT NULL,
    tour_start_time    DATE NOT NULL,
    tour_avaibility_id CHAR(3) NOT NULL
);

ALTER TABLE tour
    ADD CONSTRAINT chk_wheelchairaccess CHECK ( tour_wheel_chair IN ( 'N', 'Y' ) );

COMMENT ON COLUMN tour.port_code IS
    'Port code';

COMMENT ON COLUMN tour.tour_no IS
    'Tour number';

COMMENT ON COLUMN tour.tour_name IS
    'Tour Name';

COMMENT ON COLUMN tour.tour_desc IS
    'The description of this particular tour on this particular port';

COMMENT ON COLUMN tour.tour_hours IS
    'total tour hours required';

COMMENT ON COLUMN tour.tour_cost IS
    'the total cost of tour per person';

COMMENT ON COLUMN tour.tour_wheel_chair IS
    'wheel chair access on this tour - Y/N for Yes/No';

COMMENT ON COLUMN tour.tour_start_time IS
    'Tour start time';

COMMENT ON COLUMN tour.tour_avaibility_id IS
    'Tour Availability unique ID';

ALTER TABLE tour ADD CONSTRAINT tour_pk PRIMARY KEY ( tour_no,
                                                      port_code );

CREATE TABLE tour_availability (
    tour_avaibility_id       CHAR(3) NOT NULL,
    tour_avaibility_schedule VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN tour_availability.tour_avaibility_id IS
    'Tour Availability unique ID';

COMMENT ON COLUMN tour_availability.tour_avaibility_schedule IS
    'Tour schedule (e.g Monday, Tuesday, ..., Weekdays, Weekends)';

ALTER TABLE tour_availability ADD CONSTRAINT tour_availability_pk PRIMARY KEY ( tour_avaibility_id );

CREATE TABLE tour_comm_language (
    tour_no       CHAR(2) NOT NULL,
    port_code     CHAR(5) NOT NULL,
    language_code CHAR(2) NOT NULL
);

COMMENT ON COLUMN tour_comm_language.tour_no IS
    'Tour number';

COMMENT ON COLUMN tour_comm_language.port_code IS
    'Port code';

COMMENT ON COLUMN tour_comm_language.language_code IS
    'The code for language  stored as ISO 639-1 Alpha-2 codes';

ALTER TABLE tour_comm_language
    ADD CONSTRAINT tour_comm_language_pk PRIMARY KEY ( tour_no,
                                                       port_code,
                                                       language_code );

CREATE TABLE tour_passenger (
    tour_report_id   CHAR(4) NOT NULL,
    passenger_id     CHAR(5) NOT NULL,
    payment_received CHAR(1) NOT NULL,
    cruise_id        CHAR(4) NOT NULL
);

ALTER TABLE tour_passenger
    ADD CONSTRAINT chk_paymentreceived CHECK ( payment_received IN ( 'N', 'Y' ) );

COMMENT ON COLUMN tour_passenger.tour_report_id IS
    'surrogate key for tour report key';

COMMENT ON COLUMN tour_passenger.passenger_id IS
    'Passenger ID';

COMMENT ON COLUMN tour_passenger.payment_received IS
    'Payment received? Y/N for YES/NO ';

COMMENT ON COLUMN tour_passenger.cruise_id IS
    'Cruise ID';

ALTER TABLE tour_passenger ADD CONSTRAINT tour_passenger_pk PRIMARY KEY ( passenger_id,
                                                                          tour_report_id );

CREATE TABLE tour_report (
    tour_report_id CHAR(4) NOT NULL,
    port_code      CHAR(5) NOT NULL,
    tour_no        CHAR(2) NOT NULL,
    tour_date      DATE NOT NULL
);

COMMENT ON COLUMN tour_report.tour_report_id IS
    'surrogate key for tour report key';

COMMENT ON COLUMN tour_report.port_code IS
    'Port code';

COMMENT ON COLUMN tour_report.tour_no IS
    'Tour number';

COMMENT ON COLUMN tour_report.tour_date IS
    'the date when tour starts';

ALTER TABLE tour_report ADD CONSTRAINT tour_report_pk PRIMARY KEY ( tour_report_id );

ALTER TABLE tour_report
    ADD CONSTRAINT tour_report_nk UNIQUE ( tour_date,
                                           tour_no,
                                           port_code );

ALTER TABLE manifest
    ADD CONSTRAINT cabin_manifest FOREIGN KEY ( cabin_no,
                                                ship_code )
        REFERENCES cabin ( cabin_no,
                           ship_code );

ALTER TABLE passenger_addr
    ADD CONSTRAINT country_passengeraddr FOREIGN KEY ( country_code )
        REFERENCES country ( country_code );

ALTER TABLE port
    ADD CONSTRAINT country_port FOREIGN KEY ( country_code )
        REFERENCES country ( country_code );

ALTER TABLE ship
    ADD CONSTRAINT country_ship FOREIGN KEY ( country_code )
        REFERENCES country ( country_code );

ALTER TABLE cruise_port
    ADD CONSTRAINT cruise_cruiseport FOREIGN KEY ( cruise_id )
        REFERENCES cruise ( cruise_id );

ALTER TABLE manifest
    ADD CONSTRAINT cruise_manifest FOREIGN KEY ( cruise_id )
        REFERENCES cruise ( cruise_id );

ALTER TABLE tour_passenger
    ADD CONSTRAINT cruise_tourpassenger FOREIGN KEY ( cruise_id )
        REFERENCES cruise ( cruise_id );

ALTER TABLE passenger
    ADD CONSTRAINT guardian_ward FOREIGN KEY ( guardian_id )
        REFERENCES passenger ( passenger_id );

ALTER TABLE passenger
    ADD CONSTRAINT language_passenger FOREIGN KEY ( language_code )
        REFERENCES language ( language_code );

ALTER TABLE tour_comm_language
    ADD CONSTRAINT language_tourcommlanguage FOREIGN KEY ( language_code )
        REFERENCES language ( language_code );

ALTER TABLE ship
    ADD CONSTRAINT operator_ship FOREIGN KEY ( operator_id )
        REFERENCES operator ( operator_id );

ALTER TABLE manifest
    ADD CONSTRAINT passenger_manifest FOREIGN KEY ( passenger_id )
        REFERENCES passenger ( passenger_id );

ALTER TABLE tour_passenger
    ADD CONSTRAINT passenger_tourpassenger FOREIGN KEY ( passenger_id )
        REFERENCES passenger ( passenger_id );

ALTER TABLE passenger
    ADD CONSTRAINT passengeraddress_passenger FOREIGN KEY ( passenger_addr_code )
        REFERENCES passenger_addr ( passenger_addr_code );

ALTER TABLE cruise_port
    ADD CONSTRAINT port_cruiseport FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE port_temp
    ADD CONSTRAINT port_porttemp FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE tour
    ADD CONSTRAINT port_tour FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE cabin
    ADD CONSTRAINT ship_cabin FOREIGN KEY ( ship_code )
        REFERENCES ship ( ship_code );

ALTER TABLE cruise
    ADD CONSTRAINT ship_cruise FOREIGN KEY ( ship_code )
        REFERENCES ship ( ship_code );

ALTER TABLE tour_comm_language
    ADD CONSTRAINT tour_tourcommlanguage FOREIGN KEY ( tour_no,
                                                       port_code )
        REFERENCES tour ( tour_no,
                          port_code );

ALTER TABLE tour_report
    ADD CONSTRAINT tour_tourreport FOREIGN KEY ( tour_no,
                                                 port_code )
        REFERENCES tour ( tour_no,
                          port_code );

ALTER TABLE tour
    ADD CONSTRAINT touravailability_tour FOREIGN KEY ( tour_avaibility_id )
        REFERENCES tour_availability ( tour_avaibility_id );

ALTER TABLE tour_passenger
    ADD CONSTRAINT tourreport_tourpassenger FOREIGN KEY ( tour_report_id )
        REFERENCES tour_report ( tour_report_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            17
-- CREATE INDEX                             0
-- ALTER TABLE                             47
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL off
set echo off